services:
  HeimrichHannot\NewsLeisureBundle\EventListener\ReaderGoogleMapBeforeRenderEventListener:
    tags:
      - { name: kernel.event_listener, event: huh.google_maps.event.reader_before_render, method: modifyKMLMap }